---
title: "Final_PFR_Scraper"
output: html_document
---

###Load our packages
```{r}
library(rvest)
library(stringr)
library(tidyverse)
library(tidyr)
library(glue)
library(dplyr)
```

###Scraper
```{r}
###List of team abbreviations in pfr
teams = list("crd",
"atl",
"rav",
"buf",
"car",
"chi",
"cin",
"cle",
"dal",
"den",
"det",
"gnb",
"htx",
"clt",
"jax",
"kan",
"sdg",
"ram",
"rai",
"mia",
"min",
"nor",
"nwe",
"nyg",
"nyj",
"phi",
"pit",
"sea",
"sfo",
"tam",
"oti",
"was"
)

###List of years
years = list("2006",
             "2007",
             "2008",
             "2009",
             "2010",
             "2011",
             "2012",
             "2013",
             "2014",
             "2015",
             "2016",
             "2017",
             "2018",
             "2019",
             "2020",
             "2021")

###Loop to create  urls to scrape
url <- capture.output(
  
  for (n in teams) {
    for (a in years) {
  
    ###URL of interest
   print(paste0("https://www.pro-football-reference.com/teams/",n,"/",a,".htm"))
    

  }
})

###Remove uneeded strings
url <- url %>%
  noquote() %>%
  substr(6,100) %>%
  noquote()
url_list <- gsub('"', '', url)

url_list
```

```{r}
coordinator_scraper <- function(urls) {
  
url   <- read_html(urls)
  
A <- url %>%
  html_nodes("p") %>%
        html_text() %>%
  as.data.frame() %>%
  rename("O_Coord" = ".") %>%
  filter(across(O_Coord, ~ grepl('Offensive Coordinator', .))) 

A <- ifelse(length(A$O_Coord) < 1, 
       url %>%
       html_nodes("p") %>%
       html_text() %>%
       as.data.frame() %>%
       rename("O_Coord" = ".") %>%
       filter(across(O_Coord, ~ grepl('Coach:', .))) ,
       A) %>%
  as.data.frame()

colnames(A)[1] <- "O_Coord"

B <- url %>%
  html_nodes("p") %>%
        html_text() %>%
  as.data.frame() %>%
  rename("D_Coord" = ".") %>%
  filter(across(D_Coord, ~ grepl('Defensive Coordinator', .))) 

B <- ifelse(length(B$D_Coord) < 1, 
       url %>%
       html_nodes("p") %>%
       html_text() %>%
       as.data.frame() %>%
       rename("D_Coord" = ".") %>%
       filter(across(D_Coord, ~ grepl('Coach:', .))) ,
       B) %>%
  as.data.frame()

colnames(B)[1] <- "D_Coord"

C <-url %>%
  html_nodes("p") %>%
        html_text() %>%
  as.data.frame() %>%
  rename("Team" = ".") %>%
  filter(across(Team, ~ grepl('Franchise', .))) 

D <-url %>%
  html_nodes("p") %>%
        html_text() %>%
  as.data.frame() %>%
  rename("Season" = ".") %>%
  filter(across(Season, ~ grepl('Statistics', .))) 

data <- cbind(A,B,C, D)

return(data)

}

###Create empty data frame to store data
empty <- data.frame()

###Create loop that will go through our urls and return injuryies
for (x in url_list) {

output <- coordinator_scraper(x)

empty <- rbind(empty, output)

}

###Our data
empty %>%
  arrange(Team)
```

#Clean data
```{r}
Cleaned_Data <- empty 

#remove uneeded data
Cleaned_Data$O_Coord <- gsub("Offensive Coordinator: ","", Cleaned_Data$O_Coord)
Cleaned_Data$O_Coord <- gsub("Coach: \n ","", Cleaned_Data$O_Coord)
Cleaned_Data$D_Coord <- gsub("Defensive Coordinator: ","", Cleaned_Data$D_Coord)
Cleaned_Data$D_Coord <- gsub("Coach: \n ","", Cleaned_Data$D_Coord)
Cleaned_Data$Team    <- gsub("Franchise Pages","", Cleaned_Data$Team)

#clean season column
Cleaned_Data$Season <- str_sub(Cleaned_Data$Season, 1, 4) 
Cleaned_Data$Season <- as.numeric(Cleaned_Data$Season)

#clean coordinator columns that have records because HC is the coordinator
Cleaned_Data$O_Coord <- gsub("[[:digit:]]+","",Cleaned_Data$O_Coord)
Cleaned_Data$O_Coord <- gsub("(--)","",Cleaned_Data$O_Coord)
Cleaned_Data$O_Coord <- gsub(paste(c("[(]", "[)]"), collapse = "|"), "", Cleaned_Data$O_Coord)

Cleaned_Data$D_Coord <- gsub("[[:digit:]]+","",Cleaned_Data$D_Coord)
Cleaned_Data$D_Coord <- gsub("--","",Cleaned_Data$D_Coord)
Cleaned_Data$D_Coord <- gsub(paste(c("[(]", "[)]"), collapse = "|"), "", Cleaned_Data$D_Coord)

Cleaned_Data <- Cleaned_Data %>%
  rename("Coord_O" = O_Coord) %>%
  rename("Coord_D" = D_Coord)

#Make data long for merging with PBP
Cleaned_Data <- Cleaned_Data %>%
 pivot_longer(
   cols = starts_with("Coord"),
   names_to = "Coord",
   names_prefix = "Season",
   values_to = "Coordinator",
   values_drop_na = TRUE
 ) %>%
  rename("Side_of_Ball" = "Coord") %>%
  mutate(Side_of_Ball = ifelse(Side_of_Ball == "Coord_O", "Offense", "Defense"))

#save data
write_rds(Cleaned_Data, "Coordinator_Data.rds")

Cleaned_Data %>%
  filter(Season == "2020")
```








